import React, { useEffect, useState } from "react";
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, PieChart, Pie, Cell, Legend } from "recharts";

const COLORS = ['#8b5cf6', '#0ea5e9', '#f43f5e', '#f59e0b', '#10b981', '#6366f1'];

export default function VisualReport({ summary, report, onClose }) {
  const [isRendered, setIsRendered] = useState(false);

  useEffect(() => {
    // Slight delay to ensure Recharts has fully animated/rendered before triggering print
    setIsRendered(true);
    const timer = setTimeout(() => {
      window.print();
    }, 1000);
    
    // Add event listener to close the report view automatically after print dialog closes
    const handleAfterPrint = () => {
        onClose();
    };
    window.addEventListener("afterprint", handleAfterPrint);

    return () => {
      clearTimeout(timer);
      window.removeEventListener("afterprint", handleAfterPrint);
    };
  }, [onClose]);

  const columns = Object.keys(summary.columns || {});
  const numericColumns = columns.filter((col) => summary.columns[col].stats.mean !== undefined);
  const categoricalColumns = columns.filter((col) => summary.columns[col].stats.mean === undefined);

  // Pick top numeric and categorical column for simple summary charts
  const primaryNumeric = numericColumns.length > 0 ? numericColumns[0] : null;
  const primaryCategorical = categoricalColumns.length > 0 ? categoricalColumns[0] : null;

  // Formatting chart data
  const chartData = summary.preview.slice(0, 15).map(row => {
      const formatted = {...row};
      if (primaryCategorical && row[primaryCategorical] !== null) formatted[primaryCategorical] = String(row[primaryCategorical]);
      if (primaryNumeric && row[primaryNumeric] !== null) formatted[primaryNumeric] = Number(row[primaryNumeric]);
      return formatted;
  });

  const parseMarkdown = (text) => {
    if (!text) return "No data provided.";
    return text.split("\n").map((line, idx) => {
      let content = line;
      // Bold
      content = content.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
      
      if (line.startsWith("### ")) return <h4 key={idx} style={{ marginTop: "1.5rem", marginBottom: "0.5rem", color: "#1e293b", fontSize: "1.1rem" }} dangerouslySetInnerHTML={{__html: content.replace("### ", "")}}></h4>;
      if (line.startsWith("## ")) return <h3 key={idx} style={{ marginTop: "2rem", marginBottom: "0.5rem", color: "#0f172a", fontSize: "1.3rem", borderBottom: "1px solid #e2e8f0", paddingBottom: "0.25rem" }} dangerouslySetInnerHTML={{__html: content.replace("## ", "")}}></h3>;
      if (line.startsWith("# ")) return <h2 key={idx} style={{ marginTop: "2rem", marginBottom: "1rem", color: "#0f172a", fontSize: "1.6rem" }} dangerouslySetInnerHTML={{__html: content.replace("# ", "")}}></h2>;
      if (line.trim().startsWith("- ") || line.trim().startsWith("* ")) return <li key={idx} style={{ marginLeft: "1.5rem", marginBottom: "0.25rem", color: "#334155", fontSize: "0.95rem" }} dangerouslySetInnerHTML={{__html: content.trim().substring(2)}}></li>;
      if (!line.trim()) return <div key={idx} style={{ height: "0.5rem" }} />;
      return <p key={idx} style={{ margin: "0 0 0.75rem 0", color: "#334155", fontSize: "0.95rem", lineHeight: "1.6" }} dangerouslySetInnerHTML={{__html: content}}></p>;
    });
  };

  if (!isRendered) {
      return <div style={{ position: "fixed", top: 0, left: 0, right: 0, bottom: 0, background: "var(--bg-dark)", display: "flex", justifyContent: "center", alignItems: "center", zIndex: 9999 }}>
          <div className="loader-spinner"></div>
      </div>;
  }

  return (
    <div className="print-container" style={{ position: "absolute", top: 0, left: 0, right: 0, minHeight: "100vh", backgroundColor: "white", zIndex: 9999, color: "black", padding: "2in 1in" }}>
      
      {/* Page 1: Title & Executive Summary */}
      <div style={{ pageBreakAfter: "always" }}>
        <div style={{ borderBottom: "4px solid #8b5cf6", paddingBottom: "1rem", marginBottom: "3rem" }}>
            <h1 style={{ fontSize: "3rem", margin: "0 0 0.5rem 0", color: "#0f172a" }}>Data Analytics Report</h1>
            <p style={{ fontSize: "1.2rem", color: "#64748b", margin: 0 }}>Generated by VibeData AI Assistant</p>
            <p style={{ fontSize: "0.9rem", color: "#94a3b8", marginTop: "2rem" }}>Date: {new Date().toLocaleDateString()}</p>
        </div>

        <div style={{ marginBottom: "3rem" }}>
            {parseMarkdown(report?.project_brief || "## Executive Summary\nNo scoping report generated.")}
        </div>
        
        <div style={{ marginBottom: "3rem" }}>
            {parseMarkdown(report?.business_questions)}
        </div>
      </div>

      {/* Page 2: Data Profile & Visuals */}
      <div>
        <h2 style={{ fontSize: "1.6rem", color: "#0f172a", borderBottom: "1px solid #e2e8f0", paddingBottom: "0.5rem", marginBottom: "2rem" }}>Data Profile & Statistics</h2>
        
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: "1rem", marginBottom: "2rem" }}>
            <div style={{ padding: "1rem", backgroundColor: "#f8fafc", borderRadius: "8px", border: "1px solid #e2e8f0" }}>
                <div style={{ fontSize: "0.8rem", color: "#64748b", textTransform: "uppercase" }}>Total Rows</div>
                <div style={{ fontSize: "1.5rem", fontWeight: "bold", color: "#0f172a" }}>{(summary.row_count || 0).toLocaleString()}</div>
            </div>
            <div style={{ padding: "1rem", backgroundColor: "#f8fafc", borderRadius: "8px", border: "1px solid #e2e8f0" }}>
                <div style={{ fontSize: "0.8rem", color: "#64748b", textTransform: "uppercase" }}>Total Columns</div>
                <div style={{ fontSize: "1.5rem", fontWeight: "bold", color: "#0f172a" }}>{summary.column_count || 0}</div>
            </div>
            <div style={{ padding: "1rem", backgroundColor: "#f8fafc", borderRadius: "8px", border: "1px solid #e2e8f0" }}>
                <div style={{ fontSize: "0.8rem", color: "#64748b", textTransform: "uppercase" }}>Missing Values</div>
                <div style={{ fontSize: "1.5rem", fontWeight: "bold", color: "#0f172a" }}>{columns.reduce((sum, col) => sum + (summary.columns[col].null_count || 0), 0).toLocaleString()}</div>
            </div>
        </div>

        {primaryNumeric && primaryCategorical && (
            <div style={{ display: "flex", flexDirection: "column", gap: "3rem", marginTop: "3rem" }}>
                <div>
                    <h3 style={{ fontSize: "1.2rem", color: "#334155", marginBottom: "1rem" }}>{primaryNumeric} by {primaryCategorical}</h3>
                    <div style={{ height: "300px", width: "100%" }}>
                        <ResponsiveContainer width="100%" height="100%">
                            <BarChart data={chartData} margin={{ top: 5, right: 10, left: -20, bottom: 0 }}>
                                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                                <XAxis dataKey={primaryCategorical} stroke="#64748b" style={{ fontSize: "0.7rem" }} />
                                <YAxis stroke="#64748b" style={{ fontSize: "0.7rem" }} />
                                <Tooltip />
                                <Bar dataKey={primaryNumeric} fill="#8b5cf6" radius={[4, 4, 0, 0]} />
                            </BarChart>
                        </ResponsiveContainer>
                    </div>
                </div>

                <div>
                    <h3 style={{ fontSize: "1.2rem", color: "#334155", marginBottom: "1rem" }}>{primaryNumeric} Distribution</h3>
                    <div style={{ height: "300px", width: "100%" }}>
                        <ResponsiveContainer width="100%" height="100%">
                            <PieChart margin={{ top: 0, right: 0, left: 0, bottom: 0 }}>
                                <Tooltip />
                                <Pie
                                    data={chartData}
                                    cx="50%"
                                    cy="50%"
                                    outerRadius={100}
                                    dataKey={primaryNumeric}
                                    nameKey={primaryCategorical}
                                >
                                {chartData.map((entry, idx) => (
                                    <Cell key={`cell-${idx}`} fill={COLORS[idx % COLORS.length]} />
                                ))}
                                </Pie>
                                <Legend layout="horizontal" verticalAlign="bottom" align="center" wrapperStyle={{ fontSize: "0.8rem" }} />
                            </PieChart>
                        </ResponsiveContainer>
                    </div>
                </div>
            </div>
        )}
      </div>

    </div>
  );
}
